# Generated by Django 4.2.9 on 2024-02-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('9:00', '9:00 AM'), ('10:00', '10:00 AM')], max_length=5),
        ),
    ]
