# Generated by Django 4.2.9 on 2024-02-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_reviews_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='title',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
